### ISSUE TITLE
test case fails

### ISSUE THREAD

**Issue by prashantprabhakar** [koajs/workshop#18]
I just ran the **Hello world** module of the webshop. The simplest test case failed with error `  Error: expected "Content-Length" of "11", got "11"`. The complete error log mentioned below.

```
 Hello World
    1) should return hello world


  0 passing (24ms)
  1 failing

  1) Hello World
       should return hello world:
     Error: expected "Content-Length" of "11", got "11"
      at Test._assertHeader (D:\projects\techonology\node\koa\workshop\node_modules\supertest\lib\test.js:247:12)
      at Test._assertFunction (D:\projects\techonology\node\koa\workshop\node_modules\supertest\lib\test.js:281:11)
      at Test.assert (D:\projects\techonology\node\koa\workshop\node_modules\supertest\lib\test.js:171:18)
      at assert (D:\projects\techonology\node\koa\workshop\node_modules\supertest\lib\test.js:131:12)
      at D:\projects\techonology\node\koa\workshop\node_modules\supertest\lib\test.js:128:5
      at Test.Request.callback (D:\projects\techonology\node\koa\workshop\node_modules\superagent\lib\node\index.js:706:12)
      at IncomingMessage.parser (D:\projects\techonology\node\koa\workshop\node_modules\superagent\lib\node\index.js:906:18)
      at endReadableNT (_stream_readable.js:1101:12)
      at process._tickCallback (internal/process/next_tick.js:114:19)
```

**Comment by RHM-DanielKlier** [comment]
This threw me off, too at first. I updated the test to check for the string "11" and then the test passed. Is this an issue with the test itself or is this caused by a change in the underlying assertion library?

**Comment by AkatQuas** [comment]
It is an issue caused by the library [supertest](https://github.com/visionmedia/supertest).

The following the an example from supertest.

```
const request = require('supertest');
const express = require('express');

const app = express();

app.get('/user', function(req, res) {
  res.status(200).json({ name: 'john' });
});

request(app)
  .get('/user')
  .expect('Content-Type', /json/)
  .expect('Content-Length', '15')
  .expect(200)
  .end(function(err, res) {
    if (err) throw err;
  });
```

The expected result in `content-length` is a `string` rather than a `number`.
