### ISSUE TITLE
Question: 04-bodies

### ISSUE THREAD

**Issue by christiansakai** [koajs/workshop#7]
Hello,

I am trying to do the bonus problem in 04-bodies. Here is my code:
```
/**
 * Create the `GET /stream` route that streams this file.
 * In node.js, the current file is available as a variable `__filename`.
 */

app.use(function* (next) {
  const stat = function (filename) {
    return done => {
      fs.stat(filename, (err, stats) => {
        done(err, stats);
      });
    }
  };

  if (this.request.path !== '/stream') return yield* next;

   this.response.type = 'application/javascript';
   this.response.length = yield stat(__filename);
   this.response.body = fs.createReadStream(__filename);
});
```

It is failing with this error log
```
  Bodies
    1) GET /stream should return a stream
    ✓ GET /json should return a JSON body


  1 passing (44ms)
  1 failing

  1) Bodies GET /stream should return a stream:
     Error: Parse Error
      at Error (native)
      at Socket.socketOnData (_http_client.js:305:20)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:110:10)
      at TCP.onread (net.js:523:20)
```

I think my `this.response.length` is wrong

**Comment by coderhaoxin** [comment]
> I think my this.response.length is wrong

try

```js
done(err, stats.size);
```

**Comment by christiansakai** [comment]
ah that works! thanks!
